name: maloc_cli
description: A CLI tool for scaffolding Flutter projects with Clean Architecture, Melos monorepo setup, and BLoC state management.
version: 1.0.0
repository: https://github.com/Farhan-S/maloc_cli
homepage: https://github.com/Farhan-S/maloc_cli

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

executables:
  maloc:
